// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SFdb.Data;

#nullable disable

namespace SFdb.Migrations
{
    [DbContext(typeof(CharacterAPIDbContext))]
    [Migration("20230709181111_Moves")]
    partial class Moves
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("SFdb.Models.Character", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("SFdb.Models.Moves", b =>
                {
                    b.Property<string>("moveId")
                        .HasColumnType("TEXT");

                    b.Property<int>("charId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("moveName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("moveNotation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("moveId");

                    b.ToTable("Moves", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
